---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-auth-proxy@kubernetescrd
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - backend.{{base_domain}}
      secretName: backend
  rules:
    - host: backend.{{ base_domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-public
  namespace: default
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd
spec:
  tls:
    - hosts:
        - backend.{{base_domain}}
      secretName: backend-tls
  rules:
    - host: backend.{{ base_domain }}
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
          - path: /media
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
---

