---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: default
type: Opaque
data:
  backend_db_name: "{{ backend_db_name | b64encode }}"
  backend_db_user: "{{ backend_db_user | b64encode }}"
  backend_db_password: "{{ backend_db_password | b64encode }}"
---

