- name: Get required roles with ansible galaxy
  local_action: command ansible-galaxy install -r roles/hetzner-server/requirements.yml
  tags: infrastructure

- name: "Add public ssh keys"
  hcloud_ssh_key:
    name: "{{ item.name }}"
    public_key: "{{ item.key }}"
    state: present
  tags: infrastructure
  loop: "{{ ssh_public_keys }}"

- name: "Create Hetzner Server"
  hcloud_server:
    location: "fsn1"
    force: true
    labels:
      type: "{{ node_type }}"
      ingress: "true"
    name: "{{ project_name }}-{{ node_type }}-{{ node_index }}"
    server_type: "{{ server_type }}"
    ssh_keys: "{{ ssh_public_keys | map(attribute='name') | list }}"
    image: ubuntu-22.04
    state: present
  loop: "{{ range(1, node_count + 1) | list }}"
  loop_control:
      index_var: node_index
  tags: infrastructure

- name: "Refresh inventory after adding machines"
  meta: refresh_inventory
  tags: infrastructure