---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: postgres
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

