---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/postgres"
---

