---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: default
type: Opaque
data:
  admin_username: "{{ postgres_admin_username | b64encode }}"
  admin_password: "{{ postgres_admin_password | b64encode }}"
---

