- name: "Create a basic Load Balancer"
  hetzner.hcloud.hcloud_load_balancer:
    name: "{{ project_name }}"
    load_balancer_type: lb11
    algorithm: round_robin
    location: fsn1
    state: present
  register: load_balancer_result
  tags: infrastructure

- name: Create a label_selector Load Balancer target
  hetzner.hcloud.hcloud_load_balancer_target:
    type: label_selector
    load_balancer: "{{ load_balancer_result.hcloud_load_balancer.id }}"
    label_selector: "ingress=true"
    state: present
  tags: infrastructure

- name: Create a basic Load Balancer service with Port 80
  hetzner.hcloud.hcloud_load_balancer_service:
    load_balancer: "{{ load_balancer_result.hcloud_load_balancer.id }}"
    protocol: tcp
    listen_port: 80
    destination_port: 30080
    state: present
  tags: infrastructure

- name: Create a basic Load Balancer service with Port 443
  hetzner.hcloud.hcloud_load_balancer_service:
      load_balancer: "{{ load_balancer_result.hcloud_load_balancer.id }}"
      protocol: tcp
      listen_port: 443
      destination_port: 30443
      state: present
  tags: infrastructure