# Forward authentication to example.com
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-proxy
  namespace: default
spec:
  forwardAuth:
    address: http://auth-proxy.default.svc.cluster.local
---

