---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        triggerUpdateLabel: "{{ ansible_date_time.iso8601_basic }}"
    spec:
      containers:
      - name: frontend
        image: {{ docker_registry_host }}/{{frontend_image_name}}:{{ frontend_version }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: github-container-registry